name: Format Code
on: [push, pull_request, workflow_dispatch]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: run YAPF to test if python code is correctly formatted
        uses: AlexanderMelde/yapf-action@master
        with:
          args: --verbose

